### PR TITLE
CI: consider warnings fatal, too

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Comment by kevmoo** [comment]
Feel free to squash/merge and delete the branch if you're happy

**Review by devoncarew — COMMENTED** [review]
`--fatal-warnings` are on by default - no need to be explicit here

**Comment by kevmoo** [comment]
> `--fatal-warnings` are on by default - no need to be explicit here

on really? TIL!

**Comment by devoncarew** [comment]
Yeah, we changed the default from `dartanalyzer`, given the opportunity to update things a bit w/ a new cli tool.

**Pull request closed without merging**
