### PR TITLE
Add utilities for different base directories

### PR DESCRIPTION
**Pull request by 4e554c4c**
See related dart-lang/sdk#41560, https://github.com/dart-lang/sdk/issues/49166#issuecomment-1223943236

Test plan:
```
$ dart test
00:01 +16: All tests passed!
```
run `dart doc` and inspect docs for correctness.

---

- [x] I’ve reviewed the contributor guide and applied the relevant portions to this PR.

### CODE REVIEW

**Comment by 4e554c4c** [comment]
note: the comment by the google bot is out of date. I have signed the CLA

**Comment by sortie** [comment]
The contributor pinged me out of band asking for a reviewer, can you route this pull request appropriately @kevmoo?

**Comment by kevmoo** [comment]
@devoncarew ?

**Comment by 4e554c4c** [comment]
ping :)

**Comment by kevmoo** [comment]
you'll have to rebase this. @devoncarew – thoughts?

**Comment by 4e554c4c** [comment]
> you'll have to rebase this.
done

**Comment by emersion** [comment]
Gentle ping @devoncarew, this would be very nice to have :)

**Comment by 4e554c4c** [comment]
the PR is once again out of date (as should be expected for one open for seven months). I will rebase again when there is an indication that the PR could be merged :)

**Comment by mosuem** [comment]
Closing as the [dart-lang/cli_util](https://github.com/dart-lang/cli_util) repository is merged into the [dart-lang/tools](https://github.com/dart-lang/tools) monorepo. Please re-open this PR there!

**Pull request closed without merging**
