### PR TITLE
Add write() and writeCharCode() to Logger

### LINKED ISSUE #41: Provide a Logger wrapper for write
The Logger class is a great abstraction over dart:io stdout and stderr, but if I want to log some text without a newline, I cannot use Logger.

This means that I cannot catch such writes when mocking Logger with a fake Logger in tests.

Logger itself uses stdout.write in its indeterminate progress indicator ([grep for stdout.write](https://github.com/dart-lang/cli_util/blob/master/lib/cli_logging.dart#L222)).

I think Logger should provide other commonly used methods from stdout, an [IOSink](https://api.dart.dev/stable/2.8.3/dart-io/IOSink-class.html), like `write()`, `writeCharCode()`, and `writeln()`.

### PR DESCRIPTION
**Pull request by srawlins**
Fixes #41 

Adding public methods to subclassable public classes is a breaking change, for implementors, so I guess this should be a major version bump?

### CODE REVIEW

**Comment by srawlins** [comment]
CC @pq, @devoncarew might one of you have to review? The migration tool tests could take advantage of this.

**Comment by srawlins** [comment]
Regarding the changing public interface of Logger, should I bump the version to 0.2.0 in this PR? Next PR?

**Comment by pq** [comment]
This or a follow-up SGTM.  Be sure and touch up the CHANGELOG while you're at it?

**Comment by srawlins** [comment]
Done!

**Pull request merged**
